hooks/EXAMPLES/FVT-exit-code-error-   updated and added some FVT-exit-code test cases

diff --git a/hooks/EXAMPLES/FVT-exit-code-error-127-001 b/hooks/EXAMPLES/FVT-exit-code-error-127-001
--- a/hooks/EXAMPLES/FVT-exit-code-error-127-001
+++ b/hooks/EXAMPLES/FVT-exit-code-error-127-001
@@ -1,7 +1,7 @@
 #!/bin/bash
-#	hooks/EXAMPLES/FVT-exit-code-error-1-001  2.109.606  2019-09-20T11:14:57.276305-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.108-7-g0df0229  
+#	hooks/EXAMPLES/FVT-exit-code-error-127-001  2.109.606  2019-09-20T11:15:02.464668-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.108-7-g0df0229  
 #	   hooks/EXAMPLES/FVT-exit-code-error-   updated and added some FVT-exit-code test cases 
-#86# hooks/EXAMPLES/FVT-exit-code-error-0-001
+#86# hooks/EXAMPLES/FVT-exit-code-error-127-001 - test case
 ###  Production standard 3.0 shellcheck
 ###  Production standard 5.1.160 Copyright
 #    Copyright (c) 2019 Bradley Allen
@@ -59,6 +59,6 @@ if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBU
 
 ###     Place test case here
 
-echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 1 - exit code 1: report test case error exit code total - ${BOLD}ERROR - ERROR${NORMAL}"
-exit 1
+echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 127 - exit code 127: report test case error 'command not found' exit code total - ${BOLD}ERROR - ERROR${NORMAL}"
+exit 127
 ###
