testing --none --hooks

diff --git a/hooks/EXAMPLES/FVT-option-none-hooks-004 b/hooks/EXAMPLES/FVT-option-none-hooks-004
--- a/hooks/EXAMPLES/FVT-option-none-hooks-004
+++ b/hooks/EXAMPLES/FVT-option-none-hooks-004
@@ -1,9 +1,9 @@
 #!/bin/bash
-#	hooks/EXAMPLES/FVT-option-none-hooks-004  2.276.1076  2020-01-21T19:13:54.661124-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  dev  uadmin  five-rpi3b.cptx86.com 2.275  
+#	hooks/EXAMPLES/FVT-option-none-hooks-004  2.334.1216  2020-01-24T00:00:28.730109-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.333-3-g105b5ba  
+#	   testing --none --hooks 
+#	hooks/EXAMPLES/FVT-option-none-001  2.276.1076  2020-01-21T19:13:41.952067-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  dev  uadmin  five-rpi3b.cptx86.com 2.275  
 #	   FVT-*    Production standard 5.3.559 Copyright 
-#	hooks/bin/TEST/git-TEST-cases.sh/FVT-option-none-hooks-004  2.267.1063  2020-01-20T08:49:41.821241-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  dev  uadmin  five-rpi3b.cptx86.com 2.266-5-g0d44d76  
-#	   hooks/bin/TEST/git-TEST-cases.sh/FVT-option-none-hooks-00{1,2,3,4}   custom test cases for FVT options #36 
-#86# hooks/bin/TEST/FVT-option-none-hooks-004  -  custom test case
+#86# hooks/bin/TEST/git-TEST-cases.sh/FVT-option-none-001  -  custom test case
 ###  Production standard 3.0 shellcheck
 ###  Production standard 5.3.559 Copyright                                    # 3.559
 #    Copyright (c) 2020 Bradley Allen                                                # 3.555
@@ -64,26 +64,33 @@ fi
 
 ###  Place test case here
 
-#  output is blank: no files w/o hooks
-touch "${0}.expected"
+#    Create a file that does not have test cases and is in the hooks directory
+if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  REPOSITORY_DIR is exported in post-commit script >${REPOSITORY_DIR}<" 1>&2 ; fi
+COMMAND_NAME=$(echo "${0}" | sed 's/^.*\///')
+touch "${REPOSITORY_DIR}"/hooks/+tmp."${COMMAND_NAME}"
+if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  COMMAND_NAME >${COMMAND_NAME}<  ${REPOSITORY_DIR}/+tmp.${COMMAND_NAME}" 1>&2 ; fi
 
 "${1}" --none --hooks 2>&1 | cut -d ']' -f 3 >"${0}".test-case-output  #  pipe [] message into "${0}".test-case-output
 
+#    Remove test file
+rm   "${REPOSITORY_DIR}"/hooks/+tmp."${COMMAND_NAME}"
+
 if [[ -s ${1} ]] ; then  #  file size is greater than zero
-  diff "${0}".expected "${0}".test-case-output >/dev/null 2>&1
+  grep "+tmp.${COMMAND_NAME}" "${0}".test-case-output >/dev/null 2>&1
   RETURN_CODE=${?}
+  if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Return code >${RETURN_CODE}<  from grep +tmp.${COMMAND_NAME} ${0}.test-case-output" 1>&2 ; fi
 else
   new_message "${LINENO}" "${RED}ERROR${WHITE}" "  File, ${1}, does not exist or is empty" 1>&2
   RETURN_CODE=2
 fi
 
 if [[ "${RETURN_CODE}" -eq 0 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - No difference with expected output - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - File without a test case was found - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
   if [[ "${DEBUG}" == "1" ]] ; then cat "${0}".test-case-output 1>&2 ; fi
   exit 0
 elif [[ ${RETURN_CODE} -eq 1 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Differences with expected output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
-  diff -y "${0}".expected "${0}".test-case-output
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - File without a test case was NOT found - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
+  cat "${0}".test-case-output
   exit 1
 else
   echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
