hooks/EXAMPLES/FVT-option-none-hooks-002   copy changes from hooks/EXAMPLES/FVT-option-none-hooks-001 to hooks/EXAMPLES/FVT-option-none-hooks-002 and move file creation in to hooks directory

diff --git a/hooks/EXAMPLES/FVT-option-none-hooks-002 b/hooks/EXAMPLES/FVT-option-none-hooks-002
--- a/hooks/EXAMPLES/FVT-option-none-hooks-002
+++ b/hooks/EXAMPLES/FVT-option-none-hooks-002
@@ -1,9 +1,7 @@
 #!/bin/bash
-#	hooks/EXAMPLES/FVT-option-none-hooks-002  2.276.1076  2020-01-21T19:13:49.335884-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  dev  uadmin  five-rpi3b.cptx86.com 2.275  
-#	   FVT-*    Production standard 5.3.559 Copyright 
-#	hooks/bin/TEST/git-TEST-cases.sh/FVT-option-none-hooks-002  2.267.1063  2020-01-20T08:49:35.257571-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  dev  uadmin  five-rpi3b.cptx86.com 2.266-5-g0d44d76  
-#	   hooks/bin/TEST/git-TEST-cases.sh/FVT-option-none-hooks-00{1,2,3,4}   custom test cases for FVT options #36 
-#86# hooks/bin/TEST/FVT-option-none-hooks-002  -  custom test case
+#	hooks/EXAMPLES/FVT-option-none-hooks-002  2.295.1170  2020-01-23T15:41:43.715201-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.294  
+#	   hooks/EXAMPLES/FVT-option-none-hooks-002   copy changes from hooks/EXAMPLES/FVT-option-none-hooks-001 to hooks/EXAMPLES/FVT-option-none-hooks-002 and move file creation in to hooks directory 
+#86# hooks/bin/TEST/git-TEST-cases.sh/FVT-option-none-hooks-002  -  custom test case
 ###  Production standard 3.0 shellcheck
 ###  Production standard 5.3.559 Copyright                                    # 3.559
 #    Copyright (c) 2020 Bradley Allen                                                # 3.555
@@ -64,26 +62,32 @@ fi
 
 ###  Place test case here
 
-#  output is blank: no files w/o hooks
-touch "${0}.expected"
+#    Create a file that does not have test cases and is in the hooks directory
+REPOSITORY_DIR=$(git rev-parse --show-toplevel)
+COMMAND_NAME=$(echo "${0}" | sed 's/^.*\///')
+touch "${REPOSITORY_DIR}"/hooks/+tmp."${COMMAND_NAME}"
 
 "${1}" -n -hooks 2>&1 | cut -d ']' -f 3 >"${0}".test-case-output  #  pipe [] message into "${0}".test-case-output
 
+#    Remove test file
+rm   "${REPOSITORY_DIR}"/hooks/+tmp."${COMMAND_NAME}"
+
 if [[ -s ${1} ]] ; then  #  file size is greater than zero
-  diff "${0}".expected "${0}".test-case-output >/dev/null 2>&1
+  grep "hooks/+tmp.${COMMAND_NAME}" "${0}".test-case-output >/dev/null 2>&1
   RETURN_CODE=${?}
+  if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Return code >${RETURN_CODE}<  from grep +tmp.${COMMAND_NAME} ${0}.test-case-output" 1>&2 ; fi
 else
   new_message "${LINENO}" "${RED}ERROR${WHITE}" "  File, ${1}, does not exist or is empty" 1>&2
   RETURN_CODE=2
 fi
 
 if [[ "${RETURN_CODE}" -eq 0 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - No difference with expected output - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - File without a test case was found - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
   if [[ "${DEBUG}" == "1" ]] ; then cat "${0}".test-case-output 1>&2 ; fi
   exit 0
 elif [[ ${RETURN_CODE} -eq 1 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Differences with expected output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
-  diff -y "${0}".expected "${0}".test-case-output
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - File without a test case was NOT found - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
+  cat "${0}".test-case-output
   exit 1
 else
   echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
