hooks/EXAMPLES/FVT-option-version-001 hooks/EXAMPLES/FVT-option-version-002 hooks/EXAMPLES/FVT-option-version-003 hooks/EXAMPLES/FVT-option-version-004 -->   updated ${FVT_TEST_INPUT}

diff --git a/hooks/EXAMPLES/FVT-option-version-004 b/hooks/EXAMPLES/FVT-option-version-004
--- a/hooks/EXAMPLES/FVT-option-version-004
+++ b/hooks/EXAMPLES/FVT-option-version-004
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	hooks/EXAMPLES/FVT-option-version-004  3.1.99.1731  2020-10-23T12:25:40.102518-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 3.1.98  
+#	   hooks/EXAMPLES/FVT-option-version-001 hooks/EXAMPLES/FVT-option-version-002 hooks/EXAMPLES/FVT-option-version-003 hooks/EXAMPLES/FVT-option-version-004 -->   updated ${FVT_TEST_INPUT}  
 #	hooks/EXAMPLES/FVT-option-version-004  3.1.50.1596  2020-05-22T10:06:23.886903-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 3.1.49  
 #	   hooks/EXAMPLES/FVT-option-version-004 -->   upgrade Production standards #49  
 #	hooks/EXAMPLES/FVT-option-version-004  2.487.1407  2020-02-01T10:01:11.813517-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.486  
@@ -93,21 +95,23 @@ fi
 
 ###  Place test case here
 
+FVT_TEST_INPUT="${1} -v"
+
 TEST_VERSION=$(head -2 "${1}" | awk '{printf $3}')
-if [[ -z "${TEST_VERSION}" ]] ; then echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - Test script setup FAIL: TEST_VERSION is zero length - ${BOLD}${RED}FAIL - FAIL${NORMAL}" ; exit 1 ; fi
+if [[ -z "${TEST_VERSION}" ]] ; then echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - Test script setup FAIL: TEST_VERSION is zero length, ${FVT_TEST_INPUT} - ${BOLD}${RED}FAIL - FAIL${NORMAL}" ; exit 1 ; fi
 TEST_NAME=$(head -2 "${1}" | awk '{printf $2}')
-if [[ -z "${TEST_NAME}" ]] ; then echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - Test script setup FAIL: TEST_NAME is zero length - ${BOLD}${RED}FAIL - FAIL${NORMAL}" ; exit 1 ; fi
+if [[ -z "${TEST_NAME}" ]] ; then echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - Test script setup FAIL: TEST_NAME is zero length, ${FVT_TEST_INPUT} - ${BOLD}${RED}FAIL - FAIL${NORMAL}" ; exit 1 ; fi
 echo "${TEST_NAME} ${TEST_VERSION=}" > "${0}.expected"
 
-"${1}" -v >"${0}".test-case-output 2>&1
+eval "${FVT_TEST_INPUT}" >"${0}".test-case-output 2>&1
 
 diff "${0}".expected "${0}".test-case-output >/dev/null 2>&1
 RETURN_CODE=${?}
 if [[ "${RETURN_CODE}" -eq 0 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${TEST_CASE} ${FILE_NAME} 0 - Version output matches version on second line - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${TEST_CASE} ${FILE_NAME} 0 - Version output matches version on second line, ${FVT_TEST_INPUT} - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
   exit 0
 elif [[ "${RETURN_CODE}" -eq 1 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - Version output does NOT match version on second line - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - Version output does NOT match version on second line, ${FVT_TEST_INPUT} - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
   diff -y "${0}".expected "${0}".test-case-output
   exit 1
 else
