close #34    EXAMPLES/SA-* FVT-*   added NO -x ${1} exit ERROR 126

diff --git a/hooks/EXAMPLES/FVT-exit-code-error-0-001 b/hooks/EXAMPLES/FVT-exit-code-error-0-001
--- a/hooks/EXAMPLES/FVT-exit-code-error-0-001
+++ b/hooks/EXAMPLES/FVT-exit-code-error-0-001
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	hooks/EXAMPLES/FVT-exit-code-error-0-001  2.138.787  2019-09-27T12:32:43.101840-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.137  
+#	   close #34    EXAMPLES/SA-* FVT-*   added NO -x ${1} exit ERROR 126 
 #	hooks/EXAMPLES/FVT-exit-code-error-0-001  2.114.615  2019-09-20T19:47:00.847737-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.113  
 #	   close #16   hooks/EXAMPLES/FVT-exit-code-error-0-001   Done 
 #86# hooks/EXAMPLES/FVT-exit-code-error-0-001
@@ -45,6 +47,13 @@ new_message() {  #  $1="${SCRIPT_NAME}"  $2="${LINENO}"  $3="DEBUG INFO ERROR WA
 }
 
 if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBUG" "  Started..." 1>&2 ; fi
+
+if [[ ! -x ${1} ]] ; then  #  #34  Command invoked does not exist or cannot execute
+  RETURN_CODE=126
+  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}ERROR - ERROR${NORMAL}"
+  exit "${RETURN_CODE}"
+fi
 
 ###     Appendix E. Exit Codes With Special Meanings
 #       Exit      Meaning                            Example                    Comments
diff --git a/hooks/EXAMPLES/FVT-exit-code-error-128-001 b/hooks/EXAMPLES/FVT-exit-code-error-128-001
--- a/hooks/EXAMPLES/FVT-exit-code-error-128-001
+++ b/hooks/EXAMPLES/FVT-exit-code-error-128-001
@@ -1,6 +1,6 @@
 #!/bin/bash
-#	hooks/EXAMPLES/FVT-exit-code-error-128-001  2.109.606  2019-09-20T11:15:04.270287-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.108-7-g0df0229  
-#	   hooks/EXAMPLES/FVT-exit-code-error-   updated and added some FVT-exit-code test cases 
+#	hooks/EXAMPLES/FVT-exit-code-error-128-001  2.138.787  2019-09-27T12:32:54.040964-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.137  
+#	   close #34    EXAMPLES/SA-* FVT-*   added NO -x ${1} exit ERROR 126 
 #86# hooks/EXAMPLES/FVT-exit-code-error-128-001 - test case
 ###  Production standard 3.0 shellcheck
 ###  Production standard 5.1.160 Copyright
@@ -45,6 +45,13 @@ new_message() {  #  $1="${SCRIPT_NAME}"  $2="${LINENO}"  $3="DEBUG INFO ERROR WA
 }
 
 if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBUG" "  Started..." 1>&2 ; fi
+
+if [[ ! -x ${1} ]] ; then  #  #34  Command invoked does not exist or cannot execute
+  RETURN_CODE=126
+  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}ERROR - ERROR${NORMAL}"
+  exit "${RETURN_CODE}"
+fi
 
 ###     Appendix E. Exit Codes With Special Meanings
 #       Exit      Meaning                            Example                    Comments
diff --git a/hooks/EXAMPLES/SA-type-tar-V7-001 b/hooks/EXAMPLES/SA-type-tar-V7-001
--- a/hooks/EXAMPLES/SA-type-tar-V7-001
+++ b/hooks/EXAMPLES/SA-type-tar-V7-001
@@ -1,8 +1,6 @@
 #!/bin/bash
-#	hooks/EXAMPLES/SA-type-tar-V7-001  2.108.598  2019-09-19T16:49:31.004176-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.107-7-gae522d0  
-#	   upgrade Version section 
-#	hooks/EXAMPLES/SA-type-tar-V7-001  2.59.423  2019-09-08T22:15:47.765379-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.58  
-#	   hooks/EXAMPLES/SA-*   add new_message 
+#	hooks/EXAMPLES/SA-type-tar-V7-001  2.138.787  2019-09-27T12:34:26.345397-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.137  
+#	   close #34    EXAMPLES/SA-* FVT-*   added NO -x ${1} exit ERROR 126 
 #86# SA-permission-grp-10000-001 - test case
 ###  Production standard 3.0 shellcheck
 ###  Production standard 5.1.160 Copyright
@@ -47,6 +45,13 @@ new_message() {  #  $1="${SCRIPT_NAME}"  $2="${LINENO}"  $3="DEBUG INFO ERROR WA
 }
 
 if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBUG" "  Started..." 1>&2 ; fi
+
+if [[ ! -x ${1} ]] ; then  #  #34  Command invoked does not exist or cannot execute
+  RETURN_CODE=126
+  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}ERROR - ERROR${NORMAL}"
+  exit "${RETURN_CODE}"
+fi
 
 ###  Place test case here
 
