#37    added color in output

diff --git a/hooks/EXAMPLES/FVT-option-version-001 b/hooks/EXAMPLES/FVT-option-version-001
--- a/hooks/EXAMPLES/FVT-option-version-001
+++ b/hooks/EXAMPLES/FVT-option-version-001
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	hooks/EXAMPLES/FVT-option-version-001  2.171.827  2019-10-01T14:43:27.976197-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.170  
+#	   #37    added color in output 
 #	hooks/EXAMPLES/FVT-option-version-001  2.138.787  2019-09-27T12:33:23.049843-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.137  
 #	   close #34    EXAMPLES/SA-* FVT-*   added NO -x ${1} exit ERROR 126 
 #86# hooks/EXAMPLES/FVT-option-version-001 - test case
@@ -15,6 +17,10 @@ if [[ "${DEBUG}" == "4" ]] ; then set -e    ; fi   # Exit command has a non-zero
 #
 BOLD=$(tput -Txterm bold)
 NORMAL=$(tput -Txterm sgr0)
+RED=$(tput    setaf 1)
+GREEN=$(tput  setaf 2)
+YELLOW=$(tput setaf 3)
+CYAN=$(tput   setaf 6)
 #    Date and time function ISO 8601
 get_date_stamp() {
   DATE_STAMP=$(date +%Y-%m-%dT%H:%M:%S.%6N%:z)
@@ -49,16 +55,16 @@ if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBU
 if [[ ! -x ${1} ]] ; then  #  #34  Command invoked does not exist or cannot execute
   RETURN_CODE=126
   new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
-  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}ERROR - ERROR${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}${CYAN}ERROR - ERROR${NORMAL}"
   exit "${RETURN_CODE}"
 fi
 
 ###  Place test case here
 
 TEST_VERSION=$(head -2 "${1}" | awk '{printf $3}')
-if [[ -z "${TEST_VERSION}" ]] ; then echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 1 - Test script setup FAIL: TEST_VERSION is zero length - ${BOLD}FAIL - FAIL${NORMAL}" ; exit 1 ; fi
+if [[ -z "${TEST_VERSION}" ]] ; then echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 1 - Test script setup FAIL: TEST_VERSION is zero length - ${BOLD}${RED}FAIL - FAIL${NORMAL}" ; exit 1 ; fi
 TEST_NAME=$(head -2 "${1}" | awk '{printf $2}')
-if [[ -z "${TEST_NAME}" ]] ; then echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 1 - Test script setup FAIL: TEST_NAME is zero length - ${BOLD}FAIL - FAIL${NORMAL}" ; exit 1 ; fi
+if [[ -z "${TEST_NAME}" ]] ; then echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 1 - Test script setup FAIL: TEST_NAME is zero length - ${BOLD}${RED}FAIL - FAIL${NORMAL}" ; exit 1 ; fi
 echo "${TEST_NAME} ${TEST_VERSION=}" > "${0}.expected"
 
 "${1}" --version > "${0}".test-case-output
@@ -66,17 +72,17 @@ echo "${TEST_NAME} ${TEST_VERSION=}" > "${0}.expected"
 diff "${0}".expected "${0}".test-case-output >/dev/null 2>&1
 RETURN_CODE=${?}
 if [[ "${RETURN_CODE}" -eq 0 ]] ; then
-  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 0 - No difference with expected output - ${BOLD}PASS - PASS${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 0 - No difference with expected output - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
   exit 0
 elif [[ "${RETURN_CODE}" -eq 1 ]] ; then
-  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 1 - Differences with expected output - ${BOLD}FAIL - FAIL${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 1 - Differences with expected output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
   diff -y "${0}".expected "${0}".test-case-output
   exit 1
 else
-  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 2 - Test script logic ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 2 - Test script logic ERROR - ${BOLD}${CYAN}ERROR - ERROR${NORMAL}"
   exit 2
 fi
 
-echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
+echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}${CYAN}ERROR - ERROR${NORMAL}"
 exit 124
 ###
