hooks/EXAMPLES/FVT-option-none-001   cleanup debugging tools to get REPOSITORY_DIR set in test cases

diff --git a/hooks/EXAMPLES/FVT-option-none-001 b/hooks/EXAMPLES/FVT-option-none-001
--- a/hooks/EXAMPLES/FVT-option-none-001
+++ b/hooks/EXAMPLES/FVT-option-none-001
@@ -1,16 +1,6 @@
 #!/bin/bash
-#	hooks/EXAMPLES/FVT-option-none-001  2.316.1192  2020-01-23T21:51:04.409071-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.315  
-#	   testing -none 
-#	hooks/EXAMPLES/FVT-option-none-001  2.313.1189  2020-01-23T20:44:14.461549-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.312  
-#	   testing --none 
-#	hooks/EXAMPLES/FVT-option-none-001  2.293.1168  2020-01-23T15:10:50.928192-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.292-1-g1084d0c  
-#	   hooks/EXAMPLES/FVT-option-none-00?   copy changes from hooks/EXAMPLES/FVT-option-none-001 to hooks/EXAMPLES/FVT-option-none-002 
-#	hooks/EXAMPLES/FVT-option-none-001  2.291.1165  2020-01-23T14:49:58.057380-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.290-2-ga4c16b2  
-#	   hooks/EXAMPLES/FVT-option-none-001   add DEBUG line and change comment 
-#	hooks/EXAMPLES/FVT-option-none-001  2.288.1160  2020-01-22T21:53:10.753597-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.287  
-#	   hooks/EXAMPLES/FVT-option-none-001   testing -n 
-#	hooks/EXAMPLES/FVT-option-none-001  2.287.1159  2020-01-22T21:33:28.883427-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.286  
-#	   hooks/EXAMPLES/FVT-option-none-001   almost finished 
+#	hooks/EXAMPLES/FVT-option-none-001  2.318.1194  2020-01-23T22:02:10.602042-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.317  
+#	   hooks/EXAMPLES/FVT-option-none-001   cleanup debugging tools to get REPOSITORY_DIR set in test cases 
 #	hooks/EXAMPLES/FVT-option-none-001  2.276.1076  2020-01-21T19:13:41.952067-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  dev  uadmin  five-rpi3b.cptx86.com 2.275  
 #	   FVT-*    Production standard 5.3.559 Copyright 
 #86# hooks/bin/TEST/git-TEST-cases.sh/FVT-option-none-001  -  custom test case
@@ -75,13 +65,9 @@ fi
 ###  Place test case here
 
 #    Create a file that does not have test cases and is not in the hooks directory
-if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  -->  it should be set from post-commit <--  REPOSITORY_DIR >${REPOSITORY_DIR}<" 1>&2 ; fi
-set -x
-pwd
-REPOSITORY_DIR=$(git -C . rev-parse --show-toplevel)
+if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  REPOSITORY_DIR is exported in post-commit script >${REPOSITORY_DIR}<" 1>&2 ; fi
 COMMAND_NAME=$(echo "${0}" | sed 's/^.*\///')
-if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  REPOSITORY_DIR >${REPOSITORY_DIR}<  COMMAND_NAME >${COMMAND_NAME}<" 1>&2 ; fi
-set +x
+if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  COMMAND_NAME >${COMMAND_NAME}<" 1>&2 ; fi
 touch "${REPOSITORY_DIR}"/+tmp."${COMMAND_NAME}"
 
 "${1}" -n 2>&1 | cut -d ']' -f 3 >"${0}".test-case-output  #  pipe [] message into "${0}".test-case-output
