Use short test case name

diff --git a/hooks/EXAMPLES/FVT-option-all-hooks-001 b/hooks/EXAMPLES/FVT-option-all-hooks-001
--- a/hooks/EXAMPLES/FVT-option-all-hooks-001
+++ b/hooks/EXAMPLES/FVT-option-all-hooks-001
@@ -1,5 +1,5 @@
 #!/bin/bash
-#	hooks/EXAMPLES/FVT-option-all-hooks-001  2.383.1272  2020-01-26T18:47:29.244798-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.382  
+#	hooks/EXAMPLES/FVT-option-all-hooks-001  2.403.1292  2020-01-26T21:39:20.790200-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.402  
 #	   Use short test case name 
 #	hooks/EXAMPLES/FVT-option-all-hooks-001  2.276.1076  2020-01-21T19:11:58.007954-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  dev  uadmin  five-rpi3b.cptx86.com 2.275  
 #	   FVT-*    Production standard 5.3.559 Copyright 
@@ -62,26 +62,32 @@ TEST_CASE_TMP_2=$(dirname -- "${TEST_CASE_TMP_1}")
 TEST_CASE_TMP_3=$(basename -- "${TEST_CASE_TMP_1}")
 TEST_CASE="${TEST_CASE_TMP_2}/${BOLD}${YELLOW}${TEST_CASE_TMP_3}${NORMAL}"
 FILE_NAME_TMP_1=$(echo "${1}" | cut -d'/' -f"${REPOSITORY_DIR_COUNT}"-)
-FILE_NAME_TMP_2=$(dirname -- "${FILE_NAME_TMP_1}")
 FILE_NAME_TMP_3=$(basename -- "${FILE_NAME_TMP_1}")
-FILE_NAME="${FILE_NAME_TMP_2}/${BOLD}${YELLOW}${FILE_NAME_TMP_3}${NORMAL}"
+FILE_NAME="${BOLD}${YELLOW}${FILE_NAME_TMP_3}${NORMAL}"
 
 if [[ ! -x ${1} ]] ; then  #  Command invoked does not exist or cannot execute
   RETURN_CODE=126
   new_message "${LINENO}" "${RED}ERROR${WHITE}" "  ${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 126 - File, ${FILE_NAME}, does not exist or have execute permission - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
   exit "${RETURN_CODE}"
 fi
 
 ###  Place test case here
 
-#  output is blank: no files w/o hooks
-touch "${0}.expected"
+#    Create a directory that includes a file that does have test cases and IS in the hooks directory
+if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  REPOSITORY_DIR is exported in post-commit script >${REPOSITORY_DIR}<" 1>&2 ; fi
+COMMAND_NAME=$(echo "${0}" | sed 's/^.*\///')
+mkdir -p "${REPOSITORY_DIR}"/hooks/+tmp_DIR_"${COMMAND_NAME}"/TEST/+tmp_CMD_"${COMMAND_NAME}"
+ln -fs   "${REPOSITORY_DIR}"/hooks/EXAMPLES/SA-setup.sh   "${REPOSITORY_DIR}"/hooks/+tmp_DIR_"${COMMAND_NAME}"/TEST/+tmp_CMD_"${COMMAND_NAME}"/SA-setup.sh
+ln -fs   "${REPOSITORY_DIR}"/hooks/EXAMPLES/SA-cleanup.sh   "${REPOSITORY_DIR}"/hooks/+tmp_DIR_"${COMMAND_NAME}"/TEST/+tmp_CMD_"${COMMAND_NAME}"/SA-cleanup.sh
+touch    "${REPOSITORY_DIR}"/hooks/+tmp_DIR_"${COMMAND_NAME}"/+tmp_CMD_"${COMMAND_NAME}"
+echo     "#!/bin/bash" >> "${REPOSITORY_DIR}"/hooks/+tmp_DIR_"${COMMAND_NAME}"/+tmp_CMD_"${COMMAND_NAME}"
+if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  COMMAND_NAME >${COMMAND_NAME}<  ${REPOSITORY_DIR}/hooks/+tmp_CMD_${COMMAND_NAME}" 1>&2 ; fi
 
-"${1}" -a --hooks 2>&1 | cut -d ']' -f 3 >"${0}".test-case-output  #  pipe [] message into "${0}".test-case-output
+"${1}" -a --hooks >"${0}".test-case-output 2>&1
 
 if [[ -s ${1} ]] ; then  #  file size is greater than zero
-  diff "${0}".expected "${0}".test-case-output >/dev/null 2>&1
+  grep "hooks/+tmp_DIR_${COMMAND_NAME}"  "${0}".test-case-output >/dev/null 2>&1
   RETURN_CODE=${?}
 else
   new_message "${LINENO}" "${RED}ERROR${WHITE}" "  File, ${1}, does not exist or is empty" 1>&2
@@ -89,17 +95,16 @@ else
 fi
 
 if [[ "${RETURN_CODE}" -eq 0 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${TEST_CASE} ${FILE_NAME} 0 - No difference with expected output - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${TEST_CASE} ${FILE_NAME} 0 - Test file w/ test cases found in hooks directory - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
   if [[ "${DEBUG}" == "1" ]] ; then cat "${0}".test-case-output 1>&2 ; fi
   exit 0
 elif [[ ${RETURN_CODE} -eq 1 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Differences with expected output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
-  diff -y "${0}".expected "${0}".test-case-output
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - Test file w/ test cases NOT found in hooks directory - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
   exit 1
 else
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 2 - Test script ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
   exit 2
 fi
-echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
+echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 124 - Test script logic ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
 exit 124
 ###
