hooks/EXAMPLES/FVT-option-none-00?   copy changes from hooks/EXAMPLES/FVT-option-none-001 to hooks/EXAMPLES/FVT-option-none-002

diff --git a/hooks/EXAMPLES/FVT-option-none-002 b/hooks/EXAMPLES/FVT-option-none-002
--- a/hooks/EXAMPLES/FVT-option-none-002
+++ b/hooks/EXAMPLES/FVT-option-none-002
@@ -1,11 +1,11 @@
 #!/bin/bash
-#	hooks/bin/TEST/git-TEST-cases.sh/FVT-option-none-002  2.253.1042  2020-01-19T00:09:04.327282-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  dev  uadmin  five-rpi3b.cptx86.com 2.252  
-#	   custom test cases for FVT options #36 
+#	hooks/EXAMPLES/FVT-option-none-002  2.293.1168  2020-01-23T15:10:53.820366-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.292-1-g1084d0c  
+#	   hooks/EXAMPLES/FVT-option-none-00?   copy changes from hooks/EXAMPLES/FVT-option-none-001 to hooks/EXAMPLES/FVT-option-none-002 
 #86# hooks/bin/TEST/git-TEST-cases.sh/FVT-option-none-002  -  custom test case
 ###  Production standard 3.0 shellcheck
-###  Production standard 5.3.555 Copyright                                    # 3.555
-#    Copyright (c) 2020 Bradley Allen                                         # 3.555
-#    MIT License is online in the repository as a file named LICENSE          # 3.555
+###  Production standard 5.3.559 Copyright                                    # 3.559
+#    Copyright (c) 2020 Bradley Allen                                                # 3.555
+#    MIT License is online in the repository as a file named LICENSE"         # 3.559
 ###  Production standard 1.3.550 DEBUG variable                                             # 3.550
 #    Order of precedence: environment variable, default code
 if [[ "${DEBUG}" == ""  ]] ; then DEBUG="0" ; fi   # 0 = debug off, 1 = debug on, 'export DEBUG=1', 'unset DEBUG' to unset environment variable (bash)
@@ -62,26 +62,32 @@ fi
 
 ###  Place test case here
 
-#  output is blank: no files w/o hooks
-touch "${0}.expected"
+#    Create a file that does not have test cases and is not in the hooks directory
+REPOSITORY_DIR=$(git rev-parse --show-toplevel)
+COMMAND_NAME=$(echo "${0}" | sed 's/^.*\///')
+touch "${REPOSITORY_DIR}"/+tmp."${COMMAND_NAME}"
 
 "${1}" --none 2>&1 | cut -d ']' -f 3 >"${0}".test-case-output  #  pipe [] message into "${0}".test-case-output
 
+#    Remove test file
+rm   "${REPOSITORY_DIR}"/+tmp."${COMMAND_NAME}"
+
 if [[ -s ${1} ]] ; then  #  file size is greater than zero
-  diff "${0}".expected "${0}".test-case-output >/dev/null 2>&1
+  grep "+tmp.${COMMAND_NAME}" "${0}".test-case-output >/dev/null 2>&1
   RETURN_CODE=${?}
+  if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Return code >${RETURN_CODE}<  from grep +tmp.${COMMAND_NAME} ${0}.test-case-output" 1>&2 ; fi
 else
   new_message "${LINENO}" "${RED}ERROR${WHITE}" "  File, ${1}, does not exist or is empty" 1>&2
   RETURN_CODE=2
 fi
 
 if [[ "${RETURN_CODE}" -eq 0 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - No difference with expected output - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - File without a test case was found - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
   if [[ "${DEBUG}" == "1" ]] ; then cat "${0}".test-case-output 1>&2 ; fi
   exit 0
 elif [[ ${RETURN_CODE} -eq 1 ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Differences with expected output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
-  diff -y "${0}".expected "${0}".test-case-output
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - File without a test case was NOT found - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
+  cat "${0}".test-case-output
   exit 1
 else
   echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
