hooks/EXAMPLES/FVT-option-usage-00?   added This script does not support -* or help or usage or version

diff --git a/hooks/EXAMPLES/FVT-option-usage-004 b/hooks/EXAMPLES/FVT-option-usage-004
--- a/hooks/EXAMPLES/FVT-option-usage-004
+++ b/hooks/EXAMPLES/FVT-option-usage-004
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	hooks/EXAMPLES/FVT-option-usage-004  2.458.1362  2020-01-30T22:33:33.700546-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.457-2-g233c482  
+#	   hooks/EXAMPLES/FVT-option-usage-00?   added This script does not support -* or help or usage or version 
 #	hooks/EXAMPLES/FVT-option-usage-004  2.369.1256  2020-01-25T19:47:40.418869-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.368  
 #	   Use short test case name 
 #	hooks/EXAMPLES/FVT-option-usage-004  2.276.1076  2020-01-21T19:14:05.670037-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  dev  uadmin  five-rpi3b.cptx86.com 2.275  
@@ -59,6 +61,14 @@ new_message() {  #  $1="${LINENO}"  $2="DEBUG INFO ERROR WARN"  $3="message"
 #    INFO
 if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "${YELLOW}INFO${WHITE}" "  Started..." 1>&2 ; fi
 
+#    This script does not support -* or help or usage or version
+if [[ "${1}" == -* ]] || [[ "${1}" == "help" ]] || [[ "${1}" == "usage" ]] || [[ "${1}" == "version" ]]  ; then
+  new_message "${LINENO}" "${RED}ERROR${WHITE}" "  Option, ${YELLOW}${1}${WHITE}, is not supported with ${SCRIPT_NAME}." 1>&2
+  #    User Hint
+  echo -e "    For more information:\n${BOLD}${YELLOW}    https://github.com/BradleyA/git-TEST-commit-automation/tree/master/hooks#git-test-commit-automation------${NORMAL}"
+  exit 1
+fi
+
 ###
 
 TEST_CASE_TMP_1=$(echo "${0}" | cut -d'/' -f"${REPOSITORY_DIR_COUNT}"-)
@@ -66,14 +76,13 @@ TEST_CASE_TMP_2=$(dirname -- "${TEST_CASE_TMP_1}")
 TEST_CASE_TMP_3=$(basename -- "${TEST_CASE_TMP_1}")
 TEST_CASE="${TEST_CASE_TMP_2}/${BOLD}${YELLOW}${TEST_CASE_TMP_3}${NORMAL}"
 FILE_NAME_TMP_1=$(echo "${1}" | cut -d'/' -f"${REPOSITORY_DIR_COUNT}"-)
-FILE_NAME_TMP_2=$(dirname -- "${FILE_NAME_TMP_1}")
 FILE_NAME_TMP_3=$(basename -- "${FILE_NAME_TMP_1}")
-FILE_NAME="${FILE_NAME_TMP_2}/${BOLD}${YELLOW}${FILE_NAME_TMP_3}${NORMAL}"
+FILE_NAME="${BOLD}${YELLOW}${FILE_NAME_TMP_3}${NORMAL}"
 
 if [[ ! -x ${1} ]] ; then  #  Command invoked does not exist or cannot execute
   RETURN_CODE=126
   new_message "${LINENO}" "${RED}ERROR${WHITE}" "  ${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 126 - File, ${FILE_NAME}, does not exist or have execute permission - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
   exit "${RETURN_CODE}"
 fi
 
@@ -88,18 +97,18 @@ if  grep -q 'USAGE' "${0}".test-case-output  ; then
       echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${TEST_CASE} ${FILE_NAME} 0 - USAGE found in output - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
       exit 0
     else
-      echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 1 - DOCUMENTATION found in output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
+      echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - DOCUMENTATION found in output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
       exit 1
     fi
   else
-    echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 1 - DESCRIPTION found in output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
+    echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - DESCRIPTION found in output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
     exit 1
   fi
 else
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 1 - USAGE not found in output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - USAGE not found in output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
   exit 1
 fi
 
-echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
+echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 124 - Test script logic ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
 exit 124
 ###
