hooks/EXAMPLES/SA-cleanup.sh hooks/EXAMPLES/SA-exit-code-error-124-002 hooks/EXAMPLES/SA-exit-code-error-2-001 hooks/EXAMPLES/SA-setup.sh -->   upgrade Production standards #49

diff --git a/hooks/EXAMPLES/SA-exit-code-error-124-002 b/hooks/EXAMPLES/SA-exit-code-error-124-002
--- a/hooks/EXAMPLES/SA-exit-code-error-124-002
+++ b/hooks/EXAMPLES/SA-exit-code-error-124-002
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	hooks/EXAMPLES/SA-exit-code-error-124-002  3.1.10.1556  2020-05-21T22:31:06.988558-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 3.1.9  
+#	   hooks/EXAMPLES/SA-cleanup.sh hooks/EXAMPLES/SA-exit-code-error-124-002 hooks/EXAMPLES/SA-exit-code-error-2-001 hooks/EXAMPLES/SA-setup.sh -->   upgrade Production standards #49  
 #	hooks/EXAMPLES/SA-exit-code-error-124-002  3.1.9.1555  2020-05-21T22:04:10.726555-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 3.1.8  
 #	   hooks/EXAMPLES/SA-exit-code-error-124-002 -->   upgrade Production standards #49  
 #	hooks/EXAMPLES/SA-exit-code-error-124-002  2.447.1341  2020-01-30T15:06:30.173280-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.446  
@@ -69,8 +71,8 @@ fi
 
 if [[ ! -x ${1} ]] ; then  #  #34  Command invoked does not exist or cannot execute
   RETURN_CODE=126
-  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}${CYAN}ERROR - ERROR${NORMAL}"
+  new_message "${LINENO}" "${RED}ERROR${WHITE}" "  ${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
   exit "${RETURN_CODE}"
 fi
 
