hooks/EXAMPLES/SA-permission-*   Use short test case name

diff --git a/hooks/EXAMPLES/SA-permission-grp-10000-001 b/hooks/EXAMPLES/SA-permission-grp-10000-001
--- a/hooks/EXAMPLES/SA-permission-grp-10000-001
+++ b/hooks/EXAMPLES/SA-permission-grp-10000-001
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	hooks/EXAMPLES/SA-permission-grp-10000-001  2.461.1371  2020-01-31T19:52:08.925784-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.460-6-gd7d45b3  
+#	   hooks/EXAMPLES/SA-permission-*   Use short test case name 
 #	hooks/EXAMPLES/SA-permission-grp-10000-001  2.447.1341  2020-01-30T15:07:17.645783-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.446  
 #	   hooks/EXAMPLES/SA-*   added This script does not support -* or help or usage or version 
 #	hooks/EXAMPLES/SA-permission-grp-10000-001  2.170.826  2019-10-01T13:52:32.669992-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.169  
@@ -63,10 +65,20 @@ if [[ "${1}" == -* ]] || [[ "${1}" == "help" ]] || [[ "${1}" == "usage" ]] || [[
   exit 1
 fi
 
-if [[ ! -x ${1} ]] ; then  #  #34  Command invoked does not exist or cannot execute
+###
+
+TEST_CASE_TMP_1=$(echo "${0}" | cut -d'/' -f"${REPOSITORY_DIR_COUNT}"-)
+TEST_CASE_TMP_2=$(dirname -- "${TEST_CASE_TMP_1}")
+TEST_CASE_TMP_3=$(basename -- "${TEST_CASE_TMP_1}")
+TEST_CASE="${TEST_CASE_TMP_2}/${BOLD}${YELLOW}${TEST_CASE_TMP_3}${NORMAL}"
+FILE_NAME_TMP_1=$(echo "${1}" | cut -d'/' -f"${REPOSITORY_DIR_COUNT}"-)
+FILE_NAME_TMP_3=$(basename -- "${FILE_NAME_TMP_1}")
+FILE_NAME="${BOLD}${YELLOW}${FILE_NAME_TMP_3}${NORMAL}"
+
+if [[ ! -x ${1} ]] ; then  #  Command invoked does not exist or cannot execute
   RETURN_CODE=126
-  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}${CYAN}ERROR - ERROR${NORMAL}"
+  new_message "${LINENO}" "${RED}ERROR${WHITE}" "  ${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 126 - File, ${FILE_NAME}, does not exist or have execute permission - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
   exit "${RETURN_CODE}"
 fi
 
@@ -80,13 +92,13 @@ FILE_GROUP_ID_NUM=$(stat -Lc %g "${1}")
 
 #    Verify file group
 if [[ "${FILE_GROUP_ID_NUM}" == "${GROUP_ID_NUM}" ]] ; then
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 0 - file permission: check group: ${FILE_GROUP_ID_NUM} - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 0 - file permission: check group: ${FILE_GROUP_ID_NUM} - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
   exit 0
 else
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 1 - file permission: check group: ${FILE_GROUP_ID_NUM} - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 1 - file permission: check group: ${FILE_GROUP_ID_NUM} - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
   exit 1
 fi
 
-echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}${CYAN}ERROR - ERROR${NORMAL}"
+echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 124 - Test script logic ERROR - ${BOLD}${CYAN}ERROR - ERROR${NORMAL}"
 exit 124
 ###
