added 86 ; upgrade Production standard 1.3.496 DEBUG variable

diff --git a/hooks/EXAMPLES/SA-permission-664-001 b/hooks/EXAMPLES/SA-permission-664-001
--- a/hooks/EXAMPLES/SA-permission-664-001
+++ b/hooks/EXAMPLES/SA-permission-664-001
@@ -1,16 +1,17 @@
 #!/bin/bash
-#	hooks/EXAMPLES/SA-permission-664-001  2.4.279  2019-09-01T15:00:15.379562-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.3-5-gaab1b24  
-#	   hooks/bin/list-git-TEST-cases.sh Rename SAST to SA for Static Analysis close #1 
-###  hooks/EXAMPLES/SA-permission-664-001 - test case
+#	hooks/EXAMPLES/SA-permission-664-001  2.46.371  2019-09-05T20:51:55.048229-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.45  
+#	   added 86 ; upgrade Production standard 1.3.496 DEBUG variable 
+#86# hooks/EXAMPLES/SA-permission-664-001 - test case
 ###  Production standard 3.0 shellcheck
 ###  Production standard 5.1.160 Copyright
 #    Copyright (c) 2019 Bradley Allen
 #    MIT License is in the online DOCUMENTATION, DOCUMENTATION URL defined below.
-###  Production standard 1.3.475 DEBUG variable
+###  Production standard 1.3.496 DEBUG variable
 #    Order of precedence: environment variable, default code
 if [[ "${DEBUG}" == ""  ]] ; then DEBUG="0" ; fi   # 0 = debug off, 1 = debug on, 'export DEBUG=1', 'unset DEBUG' to unset environment variable (bash)
 if [[ "${DEBUG}" == "2" ]] ; then set -x    ; fi   # Print trace of simple commands before they are executed
 if [[ "${DEBUG}" == "3" ]] ; then set -v    ; fi   # Print shell input lines as they are read
+if [[ "${DEBUG}" == "4" ]] ; then set -e    ; fi   # Exit command has a non-zero exit status
 #
 BOLD=$(tput -Txterm bold)
 NORMAL=$(tput -Txterm sgr0)
