#34   hooks/EXAMPLES/SA-shellcheck-001   NO -x ${1} exit ERROR 126

diff --git a/hooks/EXAMPLES/SA-shellcheck-001 b/hooks/EXAMPLES/SA-shellcheck-001
--- a/hooks/EXAMPLES/SA-shellcheck-001
+++ b/hooks/EXAMPLES/SA-shellcheck-001
@@ -1,8 +1,6 @@
 #!/bin/bash
-#	hooks/EXAMPLES/SA-shellcheck-001  2.129.773  2019-09-26T18:47:49.274626-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.128  
-#	   hooks/bin/TEST/git-TEST-cases.sh  add option test cases 
-#	hooks/EXAMPLES/SA-shellcheck-001  2.127.728  2019-09-25T12:45:55.002438-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.126-45-g68716aa  
-#	   hooks/EXAMPLES/SA-shellcheck-001   add location where to find shellcheck 
+#	hooks/EXAMPLES/SA-shellcheck-001  2.136.785  2019-09-27T11:51:37.777915-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.135-3-gb3ebede  
+#	   #34   hooks/EXAMPLES/SA-shellcheck-001   NO -x ${1} exit ERROR 126 
 #	hooks/EXAMPLES/SA-shellcheck-001  2.102.562  2019-09-19T09:07:25.594245-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.101  
 #	   close #23   hooks/EXAMPLES/SA-shellcheck-001   Done 
 #86# hooks/EXAMPLES/SA-shellcheck-001 - test case
@@ -50,6 +48,13 @@ new_message() {  #  $1="${SCRIPT_NAME}"  $2="${LINENO}"  $3="DEBUG INFO ERROR WA
 }
 
 if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBUG" "  Started..." 1>&2 ; fi
+
+if [[ ! -x ${1} ]] ; then  #  Command invoked does not exist or cannot execute
+  RETURN_CODE=126
+  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}ERROR - ERROR${NORMAL}"
+  exit "${RETURN_CODE}"
+fi
 
 ###  Place test case here
 
