hooks/EXAMPLES/SA-shellcheck-001   change SCRIPT_NAME to COMMAND_NAME to remove the path

diff --git a/hooks/EXAMPLES/SA-shellcheck-001 b/hooks/EXAMPLES/SA-shellcheck-001
--- a/hooks/EXAMPLES/SA-shellcheck-001
+++ b/hooks/EXAMPLES/SA-shellcheck-001
@@ -1,4 +1,6 @@
 #!/bin/bash
+#	hooks/EXAMPLES/SA-shellcheck-001  2.290.1162  2020-01-23T14:28:31.209796-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.289  
+#	   hooks/EXAMPLES/SA-shellcheck-001   change SCRIPT_NAME to COMMAND_NAME to remove the path 
 #	hooks/EXAMPLES/SA-shellcheck-001  2.289.1161  2020-01-22T21:57:13.475935-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.288  
 #	   hooks/EXAMPLES/SA-shellcheck-001   corrected incident cd old directory 
 #	hooks/EXAMPLES/SA-shellcheck-001  2.286.1158  2020-01-22T19:16:22.577261-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.285  
@@ -68,6 +70,10 @@ fi
 
 ###  Place test case here
 
+if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBUG" "  \$1  >${1}<  \$0  >${0}<" 1>&2 ; fi
+
+COMMAND_NAME=$(echo "${0}" | sed 's/^.*\///')
+
 #    NOTE: SA-shellcheck-001.expected file is REQUIRED in the test directory.  Either an empty file if no error are expected or a file with expected errors
 
 if [[ ! -e "${0}.expected" ]] ; then
@@ -84,8 +90,8 @@ if [[ -s ${1} ]] ; then  #  file size is greater than zero
   TMP2=$(awk '$1~/^[^#]/{print NR; exit}' "${TMP_FILE_2}")  #  Locate line number of first line without comment
   tail -n+"${TMP2}"  "${TMP_FILE_2}" >> "${TMP_FILE_1}"
   rm -f "${TMP_FILE_2}"
-  mkdir -p tmp."${SCRIPT_NAME}"
-  cd tmp."${SCRIPT_NAME}" || exit  #  shellcheck SC2103 requires || exit crap
+  mkdir -p tmp."${COMMAND_NAME}"
+  cd tmp."${COMMAND_NAME}" || exit  #  shellcheck SC2103 requires || exit crap
   cp "${TMP_FILE_1}" SA-shellcheck-001
   rm -f "${TMP_FILE_1}"
   shellcheck SA-shellcheck-001 > SA-shellcheck-001.test-case-output  #  analyse code for potential errors
@@ -93,23 +99,24 @@ if [[ -s ${1} ]] ; then  #  file size is greater than zero
   cd ..
   diff SA-shellcheck-001.expected SA-shellcheck-001.test-case-output >/dev/null 2>&1
   RETURN_CODE=${?}
+  if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBUG" "  Return code >${RETURN_CODE}<  from diff SA-shellcheck-001.expected SA-shellcheck-001.test-case-output" 1>&2 ; fi
 else
-  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "  File, ${0}, is empty" 1>&2
+  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "  File, ${1}, is empty" 1>&2
   RETURN_CODE=2
 fi
 
 if [[ "${RETURN_CODE}" -eq 0 ]] ; then
   echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - No difference with expected output - ${BOLD}${GREEN}PASS - PASS${NORMAL}"
-  rm -r ./tmp."${SCRIPT_NAME}"
+#	  rm -r ./tmp."${COMMAND_NAME}"
   exit 0
 elif [[ ${RETURN_CODE} -eq 1 ]] ; then
   echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Differences with expected output - ${BOLD}${RED}FAIL - FAIL${NORMAL}"
   diff SA-shellcheck-001.expected SA-shellcheck-001.test-case-output
   exit 1
 else 
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}${CYAN}ERROR - ERROR${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
   exit 2
 fi
-echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}${CYAN}ERROR - ERROR${NORMAL}"
+echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
 exit 124
 ###
