Use short test case name

diff --git a/hooks/EXAMPLES/SA-shellcheck-001 b/hooks/EXAMPLES/SA-shellcheck-001
--- a/hooks/EXAMPLES/SA-shellcheck-001
+++ b/hooks/EXAMPLES/SA-shellcheck-001
@@ -1,5 +1,5 @@
 #!/bin/bash
-#	hooks/EXAMPLES/SA-shellcheck-001  2.390.1279  2020-01-26T19:58:38.662542-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.389  
+#	hooks/EXAMPLES/SA-shellcheck-001  2.391.1280  2020-01-26T20:11:28.632185-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.390  
 #	   Use short test case name 
 #	hooks/EXAMPLES/SA-shellcheck-001  2.372.1260  2020-01-25T21:29:27.714249-06:00 (CST)  https://github.com/BradleyA/git-TEST-commit-automation.git  master  uadmin  five-rpi3b.cptx86.com 2.371-1-gfc4ba1f  
 #	   Production standard 5.3.559 Copyright  Production standard 1.3.550 DEBUG variable  Production standard 2.3.529 log format 
@@ -62,20 +62,20 @@ TEST_CASE_TMP_2=$(dirname -- "${TEST_CASE_TMP_1}")
 TEST_CASE_TMP_3=$(basename -- "${TEST_CASE_TMP_1}")
 TEST_CASE="${TEST_CASE_TMP_2}/${BOLD}${YELLOW}${TEST_CASE_TMP_3}${NORMAL}"
 FILE_NAME_TMP_1=$(echo "${1}" | cut -d'/' -f"${REPOSITORY_DIR_COUNT}"-)
-FILE_NAME_TMP_2=$(dirname -- "${FILE_NAME_TMP_1}")
+#       FILE_NAME_TMP_2=$(dirname -- "${FILE_NAME_TMP_1}")
 FILE_NAME_TMP_3=$(basename -- "${FILE_NAME_TMP_1}")
-FILE_NAME="${FILE_NAME_TMP_2}/${BOLD}${YELLOW}${FILE_NAME_TMP_3}${NORMAL}"
+FILE_NAME="${BOLD}${YELLOW}${FILE_NAME_TMP_3}${NORMAL}"
 
 if [[ ! -x ${1} ]] ; then  #  Command invoked does not exist or cannot execute
   RETURN_CODE=126
   new_message "${LINENO}" "${RED}ERROR${WHITE}" "  ${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 126 - File, ${FILE_NAME}, does not exist or have execute permission - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
   exit "${RETURN_CODE}"
 fi
 
 ###  Place test case here
 
-if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBUG" "  \$1  >${1}<  \$0  >${0}<" 1>&2 ; fi
+if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  \$1  >${1}<  \$0  >${0}<" 1>&2 ; fi
 
 COMMAND_NAME=$(echo "${0}" | sed 's/^.*\///')
 
@@ -104,9 +104,9 @@ if [[ -s ${1} ]] ; then  #  file size is greater than zero
   cd ..
   diff SA-shellcheck-001.expected SA-shellcheck-001.test-case-output >/dev/null 2>&1
   RETURN_CODE=${?}
-  if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBUG" "  Return code >${RETURN_CODE}<  from diff SA-shellcheck-001.expected SA-shellcheck-001.test-case-output" 1>&2 ; fi
+  if [[ "${DEBUG}" == "1" ]] ; then new_message "${LINENO}" "DEBUG" "  Return code >${RETURN_CODE}<  from diff SA-shellcheck-001.expected SA-shellcheck-001.test-case-output" 1>&2 ; fi
 else
-  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "  File, ${1}, is empty" 1>&2
+  new_message "${LINENO}" "ERROR" "  File, ${1}, is empty" 1>&2
   RETURN_CODE=2
 fi
 
@@ -119,9 +119,9 @@ elif [[ ${RETURN_CODE} -eq 1 ]] ; then
   diff SA-shellcheck-001.expected SA-shellcheck-001.test-case-output
   exit 1
 else 
-  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
+  echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} ${RETURN_CODE} - Test script ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
   exit 2
 fi
-echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
+echo "${BOLD}${YELLOW}Test case --->${NORMAL} ${0} ${FILE_NAME} 124 - Test script logic ERROR - ${BOLD}${RED}ERROR${CYAN} - ERROR${NORMAL}"
 exit 124
 ###
