hooks/post-commit  cleanup development code ; testing changes

diff --git a/post-commit b/post-commit
--- a/post-commit
+++ b/post-commit
@@ -1,14 +1,10 @@
 #!/bin/bash
-#	hooks/post-commit  3.467.716  2019-08-27T06:11:40.033261-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.466  
-#	   hooks/post-commit   testing test case exit code error total report #28 
-#	hooks/post-commit  3.466.715  2019-08-27T06:07:35.245142-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.465  
-#	   hooks/post-commit   testing test case exit code error total report #28 
+#	hooks/post-commit  3.468.717  2019-08-27T14:19:46.487173-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.467  
+#	   hooks/post-commit  cleanup development code ; testing changes 
 #	hooks/post-commit  3.440.688  2019-08-26T17:23:25.222904-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.439-1-g271f90f  
 #	   hooks/post-commit   add counting for return code > 1 #28 
 #	hooks/post-commit  3.420.661  2019-08-21T12:29:09.967766-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.419  
 #	   hooks/post-commit  modified spacing with reporting status and CPU load 
-#	hooks/post-commit  3.384.623  2019-08-20T16:39:01.979337-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.383  
-#	   hooks/post-commit  complete changes to SAST and FVT sections #26 
 ###	Create production standard TESTing using .git/hooks #26 
 #	post-commit - (git hook) run test cases if found
 #	    Loop through committed files found in COMMIT_FILE_LIST
@@ -18,12 +14,10 @@
 #	                Links *.expected (test case output) to other test cases requiring the same test case output
 #	                    Loop through _TEST_CASE
 #	                        Run _TEST_CASE
-#
 ### production standard 3.0 shellcheck
 ### production standard 5.1.160 Copyright
 #       Copyright (c) 2019 Bradley Allen
 #       MIT License is in the online DOCUMENTATION, DOCUMENTATION URL defined below.
-###
 ### production standard 1.0 DEBUG variable
 #       Order of precedence: environment variable, default code
 if [ "${DEBUG}" == "" ] ; then DEBUG="0" ; fi   # 0 = debug off, 1 = debug on, 'export DEBUG=1', 'unset DEBUG' to unset environment variable (bash)
@@ -66,10 +60,11 @@ for COMMIT_PATH_FILE_NAME in ${COMMIT_FILE_LIST} ; do
 	if [ -d "${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}" ] ; then
 		get_date_stamp ; echo -e "${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${BOLD}[INFO]  Test case directory found${NORMAL} (${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}) for ${GIT_AUTHOR_NAME} (${USER})."
 		cd "${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}"
+
 		###	SAST (Static Analysis Software Test)
 		#	run SAST-setup.sh if found
-		if [ -s "${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}/SAST-setup.sh" ] ; then			# >>> changed
-			"${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}/SAST-setup.sh" "${REPOSITORY_DIR}"			# >>> changed
+		if [ -s "${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}/SAST-setup.sh" ] ; then
+			"${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}/SAST-setup.sh" "${REPOSITORY_DIR}"
 		fi
 		#	Create list of test cases
 		SAST_TEST_CASES=$(ls -1 | grep "^SAST" | grep -v "\.")
@@ -78,26 +73,26 @@ for COMMIT_PATH_FILE_NAME in ${COMMIT_FILE_LIST} ; do
 		NO_TEST_CASES_PASS=0
 		NO_TEST_CASES_FAIL=0
 		NO_TEST_CASES_ERROR=0
-		RETURN_CODE_TEST_CASES_ERROR=""
+		TEST_CASES_ERROR_EXIT_CODE=""
 		#       Loop through test cases
 		for SAST_TEST_CASE in ${SAST_TEST_CASES} ; do
 			#       Run SAST_TEST_CASE(s)
 			if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${BOLD}[DEBUG]${NORMAL}  \${REPOSITORY_DIR}/\${COMMIT_PATH}TEST/\${COMMIT_FILE_NAME}/\${SAST_TEST_CASE} >${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}/${SAST_TEST_CASE}< \${REPOSITORY_DIR}/${COMMIT_PATH_FILE_NAME} >${REPOSITORY_DIR}/${COMMIT_PATH_FILE_NAME}<" 1>&2 ; fi
 			TEST_CASE="${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}/${SAST_TEST_CASE} ${REPOSITORY_DIR}/${COMMIT_PATH_FILE_NAME}"
 			eval "${TEST_CASE}"
-			RETURN_CODE=${?}
-			if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${BOLD}[DEBUG]${NORMAL}  \${RETURN_CODE} >${RETURN_CODE}<" 1>&2 ; fi
-			if [ ${RETURN_CODE} -eq 0 ] ; then
+			EXIT_CODE=${?}
+			if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${BOLD}[DEBUG]${NORMAL}  \${EXIT_CODE} >${EXIT_CODE}<" 1>&2 ; fi
+			if [ ${EXIT_CODE} -eq 0 ] ; then
 				NO_TEST_CASES_PASS=$((NO_TEST_CASES_PASS+1))
-			elif [ ${RETURN_CODE} -eq 1 ] ; then					# >>> changed
+			elif [ ${EXIT_CODE} -eq 1 ] ; then
 				NO_TEST_CASES_FAIL=$((NO_TEST_CASES_FAIL+1))
-			else									# >>> added			
-				NO_TEST_CASES_ERROR=$((NO_TEST_CASES_ERROR+1))			# >>> added
-				RETURN_CODE_TEST_CASES_ERROR="${RETURN_CODE_TEST_CASES_ERROR}${RETURN_CODE} "                   # >>> added
+			else
+				NO_TEST_CASES_ERROR=$((NO_TEST_CASES_ERROR+1))
+				TEST_CASES_ERROR_EXIT_CODE="${TEST_CASES_ERROR_EXIT_CODE}${EXIT_CODE} "
 			fi
 		done
 		echo -e "\n>>>	SAST: ${BOLD}${COMMIT_FILE_NAME}${NORMAL}\n   Number of test cases = ${NO_TEST_CASES}\n   Number of test cases pass = ${NO_TEST_CASES_PASS}\n   Number of test cases fail = ${NO_TEST_CASES_FAIL}\n   Number of test cases error = ${NO_TEST_CASES_ERROR}"
-		echo  "${RETURN_CODE_TEST_CASES_ERROR}" | tr ' ' '\n' | grep '[^[:blank:]]' | sort | uniq -c | sort -k 2 -n  			# >>> added
+		echo  "${TEST_CASES_ERROR_EXIT_CODE}" | tr ' ' '\n' | grep '[^[:blank:]]' | sort | uniq -c | sort -k 2 -n	#	List error exit codes and how many of each exit code
 
 		###	FVT (Function Verification Test)
 		#	run FVT-setup.sh if found
@@ -111,36 +106,35 @@ for COMMIT_PATH_FILE_NAME in ${COMMIT_FILE_LIST} ; do
 		NO_TEST_CASES_PASS=0
 		NO_TEST_CASES_FAIL=0
 		NO_TEST_CASES_ERROR=0
-		RETURN_CODE_TEST_CASES_ERROR=""
+		TEST_CASES_ERROR_EXIT_CODE=""
 		#       Loop through FVT_TEST_CASES
 		for FVT_TEST_CASE in ${FVT_TEST_CASES} ; do
 			#       Run FVT_TEST_CASE(s)
 			if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${BOLD}[DEBUG]${NORMAL}  \${REPOSITORY_DIR}/\${COMMIT_PATH}TEST/\${COMMIT_FILE_NAME}/\${FVT_TEST_CASE} >${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}/${FVT_TEST_CASE}< \${REPOSITORY_DIR}/${COMMIT_PATH_FILE_NAME} >${REPOSITORY_DIR}/${COMMIT_PATH_FILE_NAME}<" 1>&2 ; fi
 			TEST_CASE="${REPOSITORY_DIR}/${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}/${FVT_TEST_CASE} ${REPOSITORY_DIR}/${COMMIT_PATH_FILE_NAME}"
 			eval "${TEST_CASE}"
-			RETURN_CODE=${?}
-			if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${BOLD}[DEBUG]${NORMAL}  \${RETURN_CODE} >${RETURN_CODE}<" 1>&2 ; fi
-			if [ ${RETURN_CODE} -eq 0 ] ; then
+			EXIT_CODE=${?}
+			if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${BOLD}[DEBUG]${NORMAL}  \${EXIT_CODE} >${EXIT_CODE}<" 1>&2 ; fi
+			if [ ${EXIT_CODE} -eq 0 ] ; then
 				NO_TEST_CASES_PASS=$((NO_TEST_CASES_PASS+1))
-			elif  [ ${RETURN_CODE} -eq 1 ] ; then
+			elif  [ ${EXIT_CODE} -eq 1 ] ; then
 				NO_TEST_CASES_FAIL=$((NO_TEST_CASES_FAIL+1))
-                        else                                                                    # >>> added                     
-                                NO_TEST_CASES_ERROR=$((NO_TEST_CASES_ERROR+1))                  # >>> added
-                                RETURN_CODE_TEST_CASES_ERROR="${RETURN_CODE_TEST_CASES_ERROR}${RETURN_CODE} "                   # >>> added
+                        else
+                                NO_TEST_CASES_ERROR=$((NO_TEST_CASES_ERROR+1))
+                                TEST_CASES_ERROR_EXIT_CODE="${TEST_CASES_ERROR_EXIT_CODE}${EXIT_CODE} "
 			fi
 		done
 		echo -e "\n>>>	FVT: ${BOLD}${COMMIT_FILE_NAME}${NORMAL}\n   Number of test cases = ${NO_TEST_CASES}\n   Number of test cases pass = ${NO_TEST_CASES_PASS}\n   Number of test cases fail = ${NO_TEST_CASES_FAIL}\n   Number of test cases error = ${NO_TEST_CASES_ERROR}"
-		echo  "${RETURN_CODE_TEST_CASES_ERROR}" | tr ' ' '\n' | grep '[^[:blank:]]' | sort | uniq -c | sort -k 2 -n  			# >>> added
+		echo  "${TEST_CASES_ERROR_EXIT_CODE}" | tr ' ' '\n' | grep '[^[:blank:]]' | sort | uniq -c | sort -k 2 -n	#	List error exit codes and how many of each exit code
 	else
 		get_date_stamp ; echo -e "${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${BOLD}[INFO]  No test case directory found${NORMAL} in ${COMMIT_PATH}TEST/${COMMIT_FILE_NAME}, for ${GIT_AUTHOR_NAME}."
 	fi
 done
-rm    "${REPOSITORY_DIR}"/hooks/COMMIT_FILE_LIST
+if [ ! "${DEBUG}" == "1" ] ; then  rm "${REPOSITORY_DIR}"/hooks/COMMIT_FILE_LIST ; fi #	Remove COMMIT_FILE_LIST if NOT in DEBUG
 
 #	process times
 echo -e "\n>>>  CPU Time    \n  user     sys"
 times
-echo -e "\n"
 
 #
 if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[DEBUG]${NORMAL}  Operation finished." 1>&2 ; fi
