SCRIPT_VERSION incident corrected and correct Test script logic ERROR message

diff --git a/EXAMPLES/FVT-option-help-005 b/EXAMPLES/FVT-option-help-005
--- a/EXAMPLES/FVT-option-help-005
+++ b/EXAMPLES/FVT-option-help-005
@@ -1,4 +1,8 @@
 #!/bin/bash
+#	hooks/EXAMPLES/FVT-option-help-005  3.488.743  2019-08-31T23:12:56.099992-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.487  
+#	   SCRIPT_VERSION incident corrected and correct Test script logic ERROR message 
+#	hooks/EXAMPLES/FVT-option-help-005  3.488.743  2019-08-31T23:10:52.295456-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.487  
+#	   SCRIPT_VERSION incident corrected and correct Test script logic ERROR message 
 #	hooks/EXAMPLES/FVT-option-help-005  3.481.736  2019-08-31T16:14:09.395646-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.480  
 #	   hooks/EXAMPLES/FVT-option-help-001 002 003 004 005 006   change tab to two spaces update Production standard 1.3.475 DEBUG variable 
 ###  hooks/EXAMPLES/FVT-option-help-005 - test case
@@ -26,9 +30,9 @@ get_date_stamp() {
 LOCALHOST=$(hostname -f)
 
 #    Version
-SCRIPT_VERSION=$(head -2 "${1}" | awk '{printf $3}')
+SCRIPT_VERSION=$(head -2 "${0}" | awk '{printf $3}')
 
-if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[DEBUG]${NORMAL}  Operation started." 1>&2 ; fi
+if [[ "${DEBUG}" == "1" ]] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[DEBUG]${NORMAL}  Operation started." 1>&2 ; fi
 
 ###  Place test case here
 
@@ -53,6 +57,6 @@ else
   exit 1
 fi
 
-echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}FAIL - FAIL${NORMAL}"
+echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
 exit 124
 ###
diff --git a/EXAMPLES/FVT-option-version-003 b/EXAMPLES/FVT-option-version-003
--- a/EXAMPLES/FVT-option-version-003
+++ b/EXAMPLES/FVT-option-version-003
@@ -1,4 +1,8 @@
 #!/bin/bash
+#	hooks/EXAMPLES/FVT-option-version-003  3.488.743  2019-08-31T23:13:27.352113-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.487  
+#	   SCRIPT_VERSION incident corrected and correct Test script logic ERROR message 
+#	hooks/EXAMPLES/FVT-option-version-003  3.488.743  2019-08-31T23:11:16.818230-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.487  
+#	   SCRIPT_VERSION incident corrected and correct Test script logic ERROR message 
 #	hooks/EXAMPLES/FVT-option-version-003  3.480.735  2019-08-31T15:43:55.771395-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.479-1-g9975d58  
 #	   hooks/EXAMPLES/FVT-option-version-001 002 003  remove tabs use two spaces add additional tests in test cases 
 ###  hooks/EXAMPLES/FVT-option-version-001 - test case
@@ -26,9 +30,9 @@ get_date_stamp() {
 LOCALHOST=$(hostname -f)
 
 #    Version
-SCRIPT_VERSION=$(head -2 "${1}" | awk '{printf $3}')
+SCRIPT_VERSION=$(head -2 "${0}" | awk '{printf $3}')
 
-if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[DEBUG]${NORMAL}  Operation started." 1>&2 ; fi
+if [[ "${DEBUG}" == "1" ]] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[DEBUG]${NORMAL}  Operation started." 1>&2 ; fi
 
 ###  Place test case here
 
@@ -43,17 +47,17 @@ echo "${TEST_NAME} ${TEST_VERSION=}" > "${0}.expected"
 diff "${0}".expected "${0}".test-case-output >/dev/null 2>&1
 RETURN_CODE=${?}
 if [[ "${RETURN_CODE}" -eq 0 ]] ; then
-  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - No difference with expected output - ${BOLD}PASS - PASS${NORMAL}"
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 0 - No difference with expected output - ${BOLD}PASS - PASS${NORMAL}"
   exit 0
 elif [[ "${RETURN_CODE}" -eq 1 ]] ; then
-  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Differences with expected output - ${BOLD}FAIL - FAIL${NORMAL}"
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 1 - Differences with expected output - ${BOLD}FAIL - FAIL${NORMAL}"
   diff -y "${0}".expected "${0}".test-case-output
   exit 1
 else
-  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script logic ERROR - ${BOLD}FAIL - FAIL${NORMAL}"
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 2 - Test script logic ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
   exit 2
 fi
 
-echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}FAIL - FAIL${NORMAL}"
+echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
 exit 124
 ###
diff --git a/EXAMPLES/SAST-permission-775-001 b/EXAMPLES/SAST-permission-775-001
--- a/EXAMPLES/SAST-permission-775-001
+++ b/EXAMPLES/SAST-permission-775-001
@@ -1,50 +1,59 @@
 #!/bin/bash
-#	hooks/EXAMPLES/SAST-permission-775-001  3.463.712  2019-08-27T05:28:35.962605-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.462  
-#	   hooks/EXAMPLES/SAST-permission-???-???  include file mode in output 
-#	hooks/EXAMPLES/SAST-permission-775-001  3.383.622  2019-08-20T16:28:43.931598-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.382 
-#	   hooks/EXAMPLES/SAST-permission-???-001 changed design flow, added DEBUG 
-### production standard 3.0 shellcheck
-### production standard 5.1.160 Copyright
-#       Copyright (c) 2019 Bradley Allen
-#       MIT License is in the online DOCUMENTATION, DOCUMENTATION URL defined below.
-###
-### production standard 1.0 DEBUG variable
-#       Order of precedence: environment variable, default code
-if [ "${DEBUG}" == "" ] ; then DEBUG="0" ; fi   # 0 = debug off, 1 = debug on, 'export DEBUG=1', 'unset DEBUG' to unset environment variable (bash)
+#	hooks/EXAMPLES/SAST-permission-775-001  3.488.743  2019-08-31T23:14:09.876400-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.487  
+#	   SCRIPT_VERSION incident corrected and correct Test script logic ERROR message 
+#	hooks/EXAMPLES/SAST-permission-775-001  3.488.743  2019-08-31T23:11:41.308239-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.487  
+#	   SCRIPT_VERSION incident corrected and correct Test script logic ERROR message 
+###  hooks/EXAMPLES/hooks/EXAMPLES/SAST-permission-775-001 - test case
+###  Production standard 3.0 shellcheck
+###  Production standard 5.1.160 Copyright
+#    Copyright (c) 2019 Bradley Allen
+#    MIT License is in the online DOCUMENTATION, DOCUMENTATION URL defined below.
+###  Production standard 1.3.475 DEBUG variable
+#    Order of precedence: environment variable, default code
+if [[ "${DEBUG}" == ""  ]] ; then DEBUG="0" ; fi   # 0 = debug off, 1 = debug on, 'export DEBUG=1', 'unset DEBUG' to unset environment variable (bash)
+if [[ "${DEBUG}" == "2" ]] ; then set -x    ; fi   # Print trace of simple commands before they are executed
+if [[ "${DEBUG}" == "3" ]] ; then set -v    ; fi   # Print shell input lines as they are read
+#
 BOLD=$(tput -Txterm bold)
 NORMAL=$(tput -Txterm sgr0)
-#       Date and time function ISO 8601
-get_date_stamp() {
-DATE_STAMP=$(date +%Y-%m-%dT%H:%M:%S.%6N%:z)
-TEMP=$(date +%Z)
-DATE_STAMP="${DATE_STAMP} (${TEMP})"
-}
-#       Fully qualified domain name FQDN hostname
-LOCALHOST=$(hostname -f)
-#       Version
-SCRIPT_VERSION=$(head -2 "${0}" | awk '{printf $3}')
-if [ "${DEBUG}" == "1" ] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[DEBUG]${NORMAL}  Operation started." 1>&2 ; fi
 
-###	Place test case here
-if [ -g "${1}" ] ; then
-	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: FILE exists and its set-group-ID bit is set - ${BOLD}FAIL - FAIL${NORMAL}"
-	exit 1
+#    Date and time function ISO 8601
+get_date_stamp() {
+  DATE_STAMP=$(date +%Y-%m-%dT%H:%M:%S.%6N%:z)
+  TEMP=$(date +%Z)
+  DATE_STAMP="${DATE_STAMP} (${TEMP})"
+}
+
+#    Fully qualified domain name FQDN hostname
+LOCALHOST=$(hostname -f)
+
+#    Version
+SCRIPT_VERSION=$(head -2 "${0}" | awk '{printf $3}')
+
+if [[ "${DEBUG}" == "1" ]] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[DEBUG]${NORMAL}  Operation started." 1>&2 ; fi
+
+###  Place test case here
+if [[ -g "${1}" ]] ; then
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 1 - file permission: FILE exists and its set-group-ID bit is set - ${BOLD}FAIL - FAIL${NORMAL}"
+  exit 1
 fi
-if [ -u "${1}" ] ; then
-	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: FILE exists and its set-user-ID bit is set - ${BOLD}FAIL - FAIL${NORMAL}"
-	exit 1
+if [[ -u "${1}" ]] ; then
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 1 - file permission: FILE exists and its set-user-ID bit is set - ${BOLD}FAIL - FAIL${NORMAL}"
+  exit 1
 fi
-if [ -k "${1}" ] ; then	#	no effect on files, but directories, all files in directory will be modifiable only by their owners (example /tmp)
-	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - directory permission: FILE exists and has its sticky bit set - ${BOLD}FAIL - FAIL${NORMAL}"
-	exit 1
+if [[ -k "${1}" ]] ; then  #  no effect on files, but directories, all files in directory will be modifiable only by their owners (example /tmp)
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 1 - directory permission: FILE exists and has its sticky bit set - ${BOLD}FAIL - FAIL${NORMAL}"
+  exit 1
 fi
-#       Verify file permissions
-if [ $(stat -Lc %a "${1}") == 775 ]; then
-	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: check mode 775 - ${BOLD}PASS - PASS${NORMAL}"
-	exit 0
+#    Verify file permissions
+if [[ $(stat -Lc %a "${1}") == 775 ]] ; then
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 0 - file permission: check mode 775 - ${BOLD}PASS - PASS${NORMAL}"
+  exit 0
 else
-	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: check mode 775 - ${BOLD}FAIL - FAIL${NORMAL}"
-	exit 1
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 1 - file permission: check mode 775 - ${BOLD}FAIL - FAIL${NORMAL}"
+  exit 1
 fi
+
+echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
 exit 124
 ###
diff --git a/EXAMPLES/SAST-shellcheck-001 b/EXAMPLES/SAST-shellcheck-001
--- a/EXAMPLES/SAST-shellcheck-001
+++ b/EXAMPLES/SAST-shellcheck-001
@@ -1,33 +1,54 @@
 #!/bin/bash
-#	hooks/EXAMPLES/SAST-shellcheck-001  3.430.672  2019-08-21T15:20:32.469981-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.429  
-#	   hooks/EXAMPLES/SAST-shellcheck-001   quick test 
-#	hooks/EXAMPLES/SAST-shellcheck-001  3.386.625  2019-08-20T17:00:07.967160-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.385  
-#	   hooks/EXAMPLES/SAST-shellcheck-001  added exit 0 
-### production standard 3.0 shellcheck
-### production standard 5.1.160 Copyright
-#       Copyright (c) 2019 Bradley Allen
-#       MIT License is in the online DOCUMENTATION, DOCUMENTATION URL defined below.
+#	#	hooks/EXAMPLES/SAST-shellcheck-001  3.488.743  2019-08-31T23:14:44.728621-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.487  
+#	#	   SCRIPT_VERSION incident corrected and correct Test script logic ERROR message 
+###  hooks/EXAMPLES/SAST-shellcheck-001 - test case
+###  Production standard 3.0 shellcheck
+###  Production standard 5.1.160 Copyright
+#    Copyright (c) 2019 Bradley Allen
+#    MIT License is in the online DOCUMENTATION, DOCUMENTATION URL defined below.
+###  Production standard 1.3.475 DEBUG variable
+#    Order of precedence: environment variable, default code
+if [[ "${DEBUG}" == ""  ]] ; then DEBUG="0" ; fi   # 0 = debug off, 1 = debug on, 'export DEBUG=1', 'unset DEBUG' to unset environment variable (bash)
+if [[ "${DEBUG}" == "2" ]] ; then set -x    ; fi   # Print trace of simple commands before they are executed
+if [[ "${DEBUG}" == "3" ]] ; then set -v    ; fi   # Print shell input lines as they are read
+#
 BOLD=$(tput -Txterm bold)
 NORMAL=$(tput -Txterm sgr0)
-###	Place test case here
 
-#	analyse code for potential errors
-shellcheck "${1}" > "${0}".test-case-output
+#    Date and time function ISO 8601
+get_date_stamp() {
+  DATE_STAMP=$(date +%Y-%m-%dT%H:%M:%S.%6N%:z)
+  TEMP=$(date +%Z)
+  DATE_STAMP="${DATE_STAMP} (${TEMP})"
+}
 
-###
+#    Fully qualified domain name FQDN hostname
+LOCALHOST=$(hostname -f)
+
+#    Version
+SCRIPT_VERSION=$(head -2 "${0}" | awk '{printf $3}')
+
+if [[ "${DEBUG}" == "1" ]] ; then get_date_stamp ; echo -e "${NORMAL}${DATE_STAMP} ${LOCALHOST} ${0}[$$] ${SCRIPT_VERSION} ${LINENO} ${USER} ${USER_ID}:${GROUP_ID} ${BOLD}[DEBUG]${NORMAL}  Operation started." 1>&2 ; fi
+
+###  Place test case here
+
+shellcheck "${1}" > "${0}".test-case-output  #  analyse code for potential errors
+
 diff "${0}".expected "${0}".test-case-output >/dev/null 2>&1
 RETURN_CODE=${?}
-if [ ${RETURN_CODE} -eq 0 ] ; then
-	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - No difference with expected output - ${BOLD}PASS - PASS${NORMAL}"
-	cat "${0}".test-case-output
-	exit 0
-elif [ ${RETURN_CODE} -eq 1 ] ; then
-	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Differences with expected output - ${BOLD}FAIL - FAIL${NORMAL}"
-	diff -y "${0}".expected "${0}".test-case-output
-	exit 1
+if [[ "${RETURN_CODE}" -eq 0 ]] ; then
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - No difference with expected output - ${BOLD}PASS - PASS${NORMAL}"
+  cat "${0}".test-case-output
+  exit 0
+elif [[ ${RETURN_CODE} -eq 1 ]] ; then
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Differences with expected output - ${BOLD}FAIL - FAIL${NORMAL}"
+  diff -y "${0}".expected "${0}".test-case-output
+  exit 1
 else 
-	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}FAIL - FAIL${NORMAL}"
-	exit 2
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
+  exit 2
 fi
+
+echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 124 - Test script logic ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
 exit 124
 ###
