hooks/bin/TEST/git-TEST-cases.sh  add option test cases

diff --git a/hooks/bin/TEST/git-TEST-cases.sh/FVT-option-a-002 b/hooks/bin/TEST/git-TEST-cases.sh/FVT-option-a-002
--- a/hooks/bin/TEST/git-TEST-cases.sh/FVT-option-a-002
+++ b/hooks/bin/TEST/git-TEST-cases.sh/FVT-option-a-002
@@ -1,12 +1,7 @@
 #!/bin/bash
-#	hooks/EXAMPLES/SA-shellcheck-001  2.129.773  2019-09-26T18:47:49.274626-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.128  
+#	hooks/bin/TEST/git-TEST-cases.sh/FVT-option-a-002  2.129.773  2019-09-26T18:47:58.041679-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.128  
 #	   hooks/bin/TEST/git-TEST-cases.sh  add option test cases 
-#	hooks/EXAMPLES/SA-shellcheck-001  2.127.728  2019-09-25T12:45:55.002438-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.126-45-g68716aa  
-#	   hooks/EXAMPLES/SA-shellcheck-001   add location where to find shellcheck 
-#	hooks/EXAMPLES/SA-shellcheck-001  2.102.562  2019-09-19T09:07:25.594245-05:00 (CDT)  https://github.com/BradleyA/git-TEST-commit-automation.git  uadmin  five-rpi3b.cptx86.com 2.101  
-#	   close #23   hooks/EXAMPLES/SA-shellcheck-001   Done 
-#86# hooks/EXAMPLES/SA-shellcheck-001 - test case
-#    shellcheck can be found: https://github.com/koalaman/shellcheck
+#86# hooks/EXAMPLES/FVT-option-a-001 - test case
 ###  Production standard 3.0 shellcheck
 ###  Production standard 5.1.160 Copyright
 #    Copyright (c) 2019 Bradley Allen
@@ -51,28 +46,25 @@ new_message() {  #  $1="${SCRIPT_NAME}"  $2="${LINENO}"  $3="DEBUG INFO ERROR WA
 
 if [[ "${DEBUG}" == "1" ]] ; then new_message "${SCRIPT_NAME}" "${LINENO}" "DEBUG" "  Started..." 1>&2 ; fi
 
-###  Place test case here
-
-#    NOTE: SA-shellcheck-001.expected file is REQUIRED in the test directory.  Either an empty file if no error are expected or a file with expected errors
-
-if [[ ! -e "${0}.expected" ]] ; then
-  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - ${0}.expected was not found.  ${BOLD}${0}.expected file is REQUIRED in the test directory.${NORMAL}  Creating file - ${BOLD}INFO - INFO${NORMAL}"
-  touch "${0}.expected"
+if [[ ! -x ${1} ]] ; then  #  Command invoked does not exist or cannot execute
+  RETURN_CODE=126
+  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "${RETURN_CODE} - File, ${1}, does not exist or have execute permission" 1>&2
+  echo "${BOLD}Test case --->${NORMAL} ${0} ${1} 126 - File, ${1}, does not exist or have execute permission - ${BOLD}ERROR - ERROR${NORMAL}"
+  exit "${RETURN_CODE}"
 fi
 
+###  Place test case here
+
+#  output is blank: no files w/o hooks
+touch "${0}.expected"
+
+"${1}" --all > "${0}".test-case-output  
+
 if [[ -s ${1} ]] ; then  #  file size is greater than zero
-  TMP_FILE_1=$(mktemp)  #  create temporary file in /tmp
-  TMP_FILE_2=$(mktemp)  #  create temporary file in /tmp
-  head -1 "${1}" > "${TMP_FILE_1}"  #  copy the first line 
-#  TMP1=$(head -c 1 "${TMP_FILE_1}")  # first character on first line in file which is assumed as the file's comment character
-  cp "${1}" "${TMP_FILE_2}"  #  make a copy of file
-  TMP2=$(awk '$1~/^[^#]/{print NR; exit}' "${TMP_FILE_2}")  #  Locate line number of first line without comment
-  tail -n+"${TMP2}"  "${TMP_FILE_2}" >> "${TMP_FILE_1}"
-  shellcheck "${TMP_FILE_1}" > "${0}".test-case-output  #  analyse code for potential errors
   diff "${0}".expected "${0}".test-case-output >/dev/null 2>&1
   RETURN_CODE=${?}
 else
-  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "  File, $[0}, is empty" 1>&2
+  new_message "${SCRIPT_NAME}" "${LINENO}" "ERROR" "  File, ${1}, does not exist or is empty" 1>&2
   RETURN_CODE=2
 fi
 
@@ -84,7 +76,7 @@ elif [[ ${RETURN_CODE} -eq 1 ]] ; then
   echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Differences with expected output - ${BOLD}FAIL - FAIL${NORMAL}"
   diff -y "${0}".expected "${0}".test-case-output
   exit 1
-else 
+else
   echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - Test script ERROR - ${BOLD}ERROR - ERROR${NORMAL}"
   exit 2
 fi
